Task/UI functionality/adminauth
Ogunjembola/TapShopping pull request #3
Opened 2023-05-14 10:18 UTC by whyhay01

2023-05-15 13:04 UTC, delaroy requested changes

2023-05-15 13:04 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/data/model/DummyData.kt
take the dummy out

2023-05-15 13:04 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/domain/ShoppingRepositoryImpl.kt
incorporate the safe api call

2023-05-15 13:04 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/ui/viewModel/AdminViewModel.kt
use the viewmodel scope

2023-05-15 13:04 UTC, delaroy commented on app/src/main/res/layout/fragment_admin.xml
use constraint layout

2023-05-15 13:04 UTC, delaroy commented on app/src/main/res/layout/fragment_create_admin.xml
same here

2023-05-15 16:37 UTC, whyhay01 commented on app/src/main/java/com/example/tapshopping/domain/ShoppingRepositoryImpl.kt
This has been resolved

2023-05-15 16:46 UTC, whyhay01 commented on app/src/main/java/com/example/tapshopping/ui/viewModel/AdminViewModel.kt
This has been resolved

2023-05-15 16:57 UTC, whyhay01 commented on app/src/main/java/com/example/tapshopping/data/model/DummyData.kt
Dummy is taken out

2023-05-16 12:12 UTC, whyhay01 commented on app/src/main/res/layout/fragment_admin.xml
Resolved

2023-05-16 12:12 UTC, whyhay01 commented on app/src/main/res/layout/fragment_create_admin.xml
Resolved

2023-05-16 12:16 UTC, delaroy approved these changes

2023-05-17 10:01 UTC, merged