Task/UIFunctionality/userAuth
Ogunjembola/TapShopping pull request #5
Opened 2023-05-15 10:05 UTC by Ogunjembola

User Authentication-> UI

2023-05-15 12:38 UTC, delaroy commented on app/build.gradle
revert to the Java SDK to 1.8

2023-05-15 12:51 UTC, delaroy requested changes

2023-05-15 12:51 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/core/ShopApplication.kt
revert back @HiltAndroidApp

2023-05-15 12:51 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/core/di/NetworkModule.kt
take off comment

2023-05-15 12:51 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/data/service/NetworkService.kt
give the body class a descriptive name and do away withe the use of dot

2023-05-15 12:51 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/domain/ShoppingRepository.kt
same here

2023-05-15 12:51 UTC, delaroy commented on app/src/main/java/com/example/tapshopping/ui/viewmodel/RegisterViewModel.kt
fuse the loading into the resource

2023-05-15 12:51 UTC, delaroy commented on app/src/main/res/layout/fragment_login.xml
don't hardcode strings use reference

2023-05-15 12:51 UTC, delaroy commented on app/src/main/res/layout/fragment_login.xml
don't use linear layout use constraint layout all through

2023-05-15 14:23 UTC, Ogunjembola commented on app/src/main/java/com/example/tapshopping/core/di/NetworkModule.kt
Fixed

2023-05-15 14:23 UTC, Ogunjembola commented on app/src/main/java/com/example/tapshopping/core/ShopApplication.kt
Fixed

2023-05-15 14:24 UTC, Ogunjembola commented on app/src/main/java/com/example/tapshopping/data/service/NetworkService.kt
Fixed

2023-05-15 14:48 UTC, Ogunjembola commented on app/src/main/java/com/example/tapshopping/ui/viewmodel/RegisterViewModel.kt
Fixed

2023-05-15 14:50 UTC, Ogunjembola commented on app/src/main/res/layout/fragment_login.xml
Fixed

2023-05-16 16:15 UTC, Ogunjembola commented on app/build.gradle
fixed

2023-05-16 16:16 UTC, Ogunjembola commented on app/src/main/java/com/example/tapshopping/domain/ShoppingRepository.kt
fixed

2023-05-16 16:16 UTC, Ogunjembola commented on app/src/main/res/layout/fragment_login.xml
fixed

2023-05-17 10:48 UTC, merged